# @package train.dataset
# YOLO dataset specific configuration

_target_: d_fine.dataset.yolo.yolo_dataset.YoloDatasetConfig

# Dataset paths
data_path: ${train.base_path}
path_to_test_data: ${train.base_path}


base_path: ${train.base_path}
task: ${train.task}
debug_img_processing: True
examples_per_epoch: null
mosaic_augs: ${train.mosaic_augs}
augs: ${train.augs}
img_config: ${train.img_config}

# Class label mapping (required for YOLO format)
label_to_name:
  0: pedestrian
  1: people
  2: bicycle
  3: car
  4: van
  5: truck
  6: tricycle
  7: awning-tricycle
  8: bus
  9: motor

